dory/dory_reconfig_handle:
  ros__parameters:
    gains:
      kp: "[1.0,1.0,1.0,1.0,1.0,1.0]"
      kd: "[2.0,2.0,2.0,2.0,2.0,2.0]"
    waypoint: 
      seeking: "[1.0,1.0,3.0,0.0,0.0,0.0]"
    configuration:
      following_waypoint: false
      following_path: true
